// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'use!underscore', 'use!backbone', 'modules/solution_view'], function($, _, Backbone, SolutionView) {
    return Backbone.View.extend({
      initialize: function() {
        console.log('init collection view');
        return this.listenTo(this.collection, 'add', this.render);
      },
      render: function(newmodel, collection, another_thing) {
        var $solutionEl, solution_view;

        $solutionEl = $('<li class="solution"/>').attr('id', newmodel.cid);
        $solutionEl.prependTo(this.$el);
        solution_view = new SolutionView({
          model: newmodel,
          el: $solutionEl[0]
        });
        return solution_view.render(newmodel);
      }
    });
  });

}).call(this);
