// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'use!underscore', 'use!backbone', 'text!templates/stats_template.html'], function($, _, Backbone, template_html) {
    return Backbone.View.extend({
      initialize: function() {
        this.$template = _.template(unescape(template_html));
        console.log('init stats model');
        return this.listenTo(this.model, 'change', this.render);
      },
      render: function(model) {
        console.log('stadt render');
        return this.$el.html(this.$template(model.toJSON()));
      }
    });
  });

}).call(this);
