// Generated by CoffeeScript 1.6.2
(function() {
  require(['jquery', 'use!underscore', 'use!backbone', 'modules/solution_collection_view'], function($, _, Backbone, SolutionCollectionView) {
    var Solution, Solutions, solutionCollectionView, solutions, worker;

    Solution = Backbone.Model.extend();
    Solutions = Backbone.Collection.extend({
      model: Solution
    });
    solutions = new Solutions();
    solutionCollectionView = new SolutionCollectionView({
      collection: solutions,
      el: $('#solutions')[0]
    });
    worker = new Worker('app/workers/worker.js');
    worker.onmessage = function(event) {
      var s;

      console.log('from worker:  ' + JSON.stringify(event.data));
      if (event.data.hasOwnProperty('solution')) {
        s = new Solution({
          position: event.data.solution
        });
        solutions.add({
          position: event.data.solution
        });
        $('#count').html(event.data.total + ' solutions, ' + event.data.uniqueGuesses + ' guesses');
      }
      if (event.data.hasOwnProperty('solutions')) {
        return console.log(solutions.toJSON());
      }
    };
    return worker.postMessage({
      test: true,
      numberOfTries: 100000
    });
  });

}).call(this);
