// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'use!underscore', 'use!backbone', 'text!templates/solution_template.html'], function($, _, Backbone, template_html) {
    return Backbone.View.extend({
      initialize: function() {
        this.$template = $(template_html).hide();
        return console.log('init model');
      },
      render: function(model, collection, thing) {
        var $row, $square, i, row, _i, _len, _ref;

        _ref = model.get('position');
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          row = _ref[i];
          $row = $(this.$template.find('tr').get(row));
          $square = $($row.find('td').get(i));
          $square.html('<div class="piece"/>');
        }
        this.$el.append(this.$template);
        return this.$template.fadeIn();
      }
    });
  });

}).call(this);
